<?php return array(
	'name' => __( '#Statistics', 'lsvrtheme' ),
	'custom_class' => 'lsvr-layout-template lsvr-layout-template-statistics',
	'content' => '[vc_row][vc_column width="1/1"][vc_column_text]
<h2>TownPress Population</h2>
[/vc_column_text][vc_row_inner][vc_column_inner width="1/3"][lsvr_counter counter_number="2568" title="Citizens"][/vc_column_inner][vc_column_inner width="1/3"][lsvr_counter counter_number="1226" title="Male Citizens"][/vc_column_inner][vc_column_inner width="1/3"][lsvr_counter counter_number="1342" title="Female Citizens"][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner width="1/3"][lsvr_counter counter_number="52" title="Average Income" number_char="k"][/vc_column_inner][vc_column_inner width="1/3"][lsvr_counter counter_number="4.5" title="Unempl. Rate" number_char="%"][/vc_column_inner][vc_column_inner width="1/3"][lsvr_counter counter_number="528" title="Senior Citizens"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row][vc_column width="1/1"][lsvr_separator type="default" whitespace_size="medium" margin_top="none" margin_bottom="medium"][/vc_column][/vc_row][vc_row][vc_column width="1/1"][vc_column_text]
<h2>Households</h2>
[/vc_column_text][vc_row_inner][vc_column_inner width="1/2"][lsvr_progressbar percentage="40" title="With Above Average Income (40%)"][lsvr_progressbar percentage="65" title="With Internet Access (65%)"][/vc_column_inner][vc_column_inner width="1/2"][lsvr_progressbar percentage="60" title="With Personal Computer (60%)"][lsvr_progressbar percentage="75" title="With At Least One Car (75%)"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row][vc_column width="1/1"][lsvr_separator type="default" margin_top="none" margin_bottom="medium"][/vc_column][/vc_row][vc_row][vc_column width="1/1"][vc_column_text]
<h2>Area</h2>
[/vc_column_text][vc_row_inner][vc_column_inner width="1/3"][lsvr_counter counter_number="72" title="Total" number_char=" sq mi"][/vc_column_inner][vc_column_inner width="1/3"][lsvr_counter counter_number="68" title="Land" number_char=" sq mi"][/vc_column_inner][vc_column_inner width="1/3"][lsvr_counter counter_number="4 sq mi" title="Water" number_char=" sq mi"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row][vc_column width="1/1"][lsvr_separator type="default" whitespace_size="medium" margin_top="none" margin_bottom="medium"][/vc_column][/vc_row][vc_row][vc_column width="1/1"][vc_column_text]
<h2>Police Department</h2>
[/vc_column_text][vc_row_inner][vc_column_inner width="1/3"][lsvr_counter counter_number="10" title="Full Time Officers"][/vc_column_inner][vc_column_inner width="1/3"][lsvr_counter counter_number="5" title="Part Time Officers"][/vc_column_inner][vc_column_inner width="1/3"][lsvr_counter counter_number="6" title="Dispatch Personnel"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]'
); ?>